### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by gonnndc** [FerDR89/desafioM4#1]
Hola Fer! 

Felicitaciones por como te quedo el desafío, me gusto mucho! 

En este desafío el foco está en la creación y uso de los componentes, y el consumo de la data desde un cms, ambas tareas las pudiste cumplir sin problemas. 

Te mando un saludo y éxitos para lo que sigue!

**Comment by FerDR89** [comment]
Hola Gon!
Muchas gracias por tus palabras y me pone contento que te haya gustado!
Saludos y éxitos para vos también!
